workflows:
  build-android:
    name: Build Android AAB
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

  build-ios:
    name: Build iOS IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      # Build sem assinatura automática para você assinar manualmente depois
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
